### ISSUE TITLE
2015-Robot-Code Is Going Public

### ISSUE THREAD

**Issue by jakekinsella** [Team4761/2015-Robot-Code#17]
Now that we are into the offseason I am changing the 2015-Robot-Code repository to be a public repository. I just wanted everyone to be aware of this.

**Comment by simon-andrews** [comment]
Now that this repo is public, does anyone have any objections if I move the generation of Javadocs over to [Travis](https://travis-ci.org/)? We could also have stuff there like a checkstyle check. The main pro is that the continuous integration server would be open to everyone, so we could all control what tasks we want to run after every commit. I can't think of any cons at the moment but maybe someone else can.

**Comment by jakekinsella** [comment]
It’s ok with me, but it is really your decision because it is your project.

Jake Kinsella
